### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by flyher** [kuitos/angular-utils#1]
![image](https://cloud.githubusercontent.com/assets/5570324/14169377/f787b6a0-f759-11e5-80f9-d627361ff934.png)

运行了一下demo里面的,报这个错误,`Cannot read property 'name' of undefined`

package.json里面用了最新的版本,不知道什么原因.

``` json
  "dependencies": {
    "angular": "^1.5.3",
    "angular-resource": "^1.5.3",
    "oclazyload": "^1.0.9",
    "angular-ui-router": "^1.0.0-alpha.1",
    "ui-router": "^1.0.0-alpha0"
  }
```

**Comment by kuitos** [comment]
应该是ui-router版本的原因。
使用 angular-ui-router 0.2.x 作依赖，最新版改动较多。
另外，不要使用angular-ui-router 跟 ui-router 是同一个库，不需要依赖两次。但是，0.2.x版本只有angular-ui-router库里有，ui-router已unpublish相关package。

**Comment by flyher** [comment]
感谢,换版本确实解决了问题.
顺便请教一下，这种方案是否适合，
`
已经用ng1写好的，每个页面封装了独立的controller和service并且包含众多css,js应用的大型项目。
也就是尽量不改原来的代码而实现这种加载方式。
`

**Comment by kuitos** [comment]
这个方案本身就是不需要改原有代码的。
不知道你们现在是怎么写的，给个代码示例？

**Comment by flyher** [comment]
![image](https://cloud.githubusercontent.com/assets/5570324/14170269/666d4b2a-f75f-11e5-8b1c-5c249350d7ac.png)
我似乎遇到了[这个](https://github.com/ocombe/ocLazyLoad/issues/135)问题。

项目有些庞大，如果需要代码事例我试着整理一个简单的demo然后贴在这里给你参考一下。

**Comment by kuitos** [comment]
截图跟你贴的链接是描述的同一个问题？
github上开个repo吧这里不好看

**Comment by flyher** [comment]
报错信息一样，我新开个repo
