### ISSUE TITLE
你好我用到你的ui-router-require-polyfill.js 有个问题想问一下

### ISSUE THREAD

**Issue by Jackie-5** [kuitos/angular-utils#3]
你好我用webpack打包你的 ui-router-require-polyfill.js 这个js后 angular会报出一个错误 

TypeError: Cannot read property 'name' of undefined 

我不太理解这个是什么原因造成的 如果有时间可以加我一下我把问题重现给你。

**Comment by kuitos** [comment]
大概能猜到你用的 ui.router 版本太高导致的 不要用1.x版本的
用这个 "angular-ui-router": "^0.2.18"

**Comment by Jackie-5** [comment]
恩 确实是这个版本的问题~ 感谢~~
